# Generated by Django 3.1 on 2021-12-21 06:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0002_auto_20211220_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['name'], 'verbose_name': 'AddCourt', 'verbose_name_plural': 'AddCourt'},
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateTimeField()),
                ('timeslot', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='court.court')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
                'ordering': ['price'],
            },
        ),
    ]
